// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWjYyUsJZ6D48hkXR3kPf-z7QD10CqJCc',
    appId: '1:500294587338:web:cc4bd999f91b2b06eeb533',
    messagingSenderId: '500294587338',
    projectId: 'app-suntec',
    authDomain: 'app-suntec.firebaseapp.com',
    storageBucket: 'app-suntec.appspot.com',
    measurementId: 'G-J82Q20E9N3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8nCQJP7zaGSxWAb96435CY6YG7QbK0U4',
    appId: '1:500294587338:android:8702879cffcda93ceeb533',
    messagingSenderId: '500294587338',
    projectId: 'app-suntec',
    storageBucket: 'app-suntec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd9v3XxRAN91v5yCTRiXWGHDRwdhs9SDQ',
    appId: '1:500294587338:ios:b013b5e03eb6d952eeb533',
    messagingSenderId: '500294587338',
    projectId: 'app-suntec',
    storageBucket: 'app-suntec.appspot.com',
    iosClientId: '500294587338-2qee1d1hhesqdikf7e416fqd24d7a167.apps.googleusercontent.com',
    iosBundleId: 'com.example.appSuntec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd9v3XxRAN91v5yCTRiXWGHDRwdhs9SDQ',
    appId: '1:500294587338:ios:b013b5e03eb6d952eeb533',
    messagingSenderId: '500294587338',
    projectId: 'app-suntec',
    storageBucket: 'app-suntec.appspot.com',
    iosClientId: '500294587338-2qee1d1hhesqdikf7e416fqd24d7a167.apps.googleusercontent.com',
    iosBundleId: 'com.example.appSuntec',
  );
}
